// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoiP2LF-PEWMe-tl4UhDzxK9GpVnwWYK0',
    appId: '1:531541602163:web:43eda23540ab2398535f06',
    messagingSenderId: '531541602163',
    projectId: 'zigonfirebase',
    authDomain: 'zigonfirebase.firebaseapp.com',
    storageBucket: 'zigonfirebase.appspot.com',
    measurementId: 'G-GYPMZW45G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7EpaeWmMRsunl24sOejFcyG-e1E6hbY',
    appId: '1:531541602163:android:cac83e910a50dd85535f06',
    messagingSenderId: '531541602163',
    projectId: 'zigonfirebase',
    storageBucket: 'zigonfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs864nki5-71KoXx-xpBSo0eQHpN2R6FA',
    appId: '1:531541602163:ios:c7f57e6c2f153ec8535f06',
    messagingSenderId: '531541602163',
    projectId: 'zigonfirebase',
    storageBucket: 'zigonfirebase.appspot.com',
    androidClientId: '531541602163-ad9pvn3fh3i830jfn4dku6r2mfkgjkrr.apps.googleusercontent.com',
    iosClientId: '531541602163-cu2c9j9ee68rqtop0tqi6hguold1iim1.apps.googleusercontent.com',
    iosBundleId: 'com.example.zigonflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs864nki5-71KoXx-xpBSo0eQHpN2R6FA',
    appId: '1:531541602163:ios:eb5667d8bc12acb6535f06',
    messagingSenderId: '531541602163',
    projectId: 'zigonfirebase',
    storageBucket: 'zigonfirebase.appspot.com',
    androidClientId: '531541602163-ad9pvn3fh3i830jfn4dku6r2mfkgjkrr.apps.googleusercontent.com',
    iosClientId: '531541602163-8r2536la65p6a48eujgo1uon4opekh1p.apps.googleusercontent.com',
    iosBundleId: 'com.fuel.zigonflutter.RunnerTests',
  );
}
